[package]
name = "injectDll"
version = "0.1.0"
authors = ["segfo <k.segfo@gmail.com>"]

[lib]
name = "apiHook"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
sharedlib = "3.1"
winapi = "0.2"
libc = "0.2"
kernel32-sys = "0.2"